import os
import re
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

VAULT_PATH = Path(os.getenv("OBSIDIAN_VAULT_PATH", "MeetingNotes"))


def _safe_filename(name: str) -> str:
    return re.sub(r'[\\/*?:"<>|]', "_", name)


def write_meeting_note(graph_data: dict) -> str:
    """
    graph_data → Obsidian 마크다운 노트 생성
    반환: 생성된 파일 경로

    project_id가 있으면 `MeetingNotes/{project_id}/` 서브폴더에 저장한다. 같은
    프로젝트의 회차 노트들이 한 폴더에 모이고, Obsidian 위키링크가 자연스럽게
    회차 간 연결을 형성한다.
    """
    project_id = graph_data.get("project_id") or "default"
    target_dir = VAULT_PATH / _safe_filename(project_id)
    target_dir.mkdir(parents=True, exist_ok=True)

    meeting_id = graph_data.get("meeting_id", "unknown")
    title = graph_data.get("title") or f"Meeting_{meeting_id[:8]}"
    date_str = graph_data.get("date") or datetime.now().strftime("%Y-%m-%d")
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    speakers = graph_data.get("speakers", [])
    topics = graph_data.get("topics", [])
    decisions = graph_data.get("decisions", [])
    action_items = graph_data.get("action_items", [])
    entities = graph_data.get("entities", [])
    summary = graph_data.get("summary", "")

    node_count = graph_data.get("node_count", 0)
    edge_count = graph_data.get("edge_count", 0)

    # ── frontmatter ──────────────────────────────────────────────────────────
    participant_list = ", ".join(s["name"] for s in speakers)
    categories = list({t.get("category", "general") for t in topics})
    tags_str = "meeting, " + ", ".join(categories)

    lines = [
        "---",
        f"meeting_id: {meeting_id}",
        f"project_id: {project_id}",
        f"date: {date_str}",
        f"title: \"{title}\"",
        f"participants: [{participant_list}]",
        f"tags: [{tags_str}]",
        "---",
        "",
        f"# {title}",
        "",
    ]

    # ── 참석자 ────────────────────────────────────────────────────────────────
    lines += ["## 참석자", ""]
    for s in speakers:
        ratio = s.get("speaking_time_ratio") or 0
        lines.append(f"- **{s['name']}** ({s.get('role', '')})"
                     + (f" — 발언 비중 {ratio:.0%}" if ratio else ""))
    lines.append("")

    # ── 핵심 주제 ─────────────────────────────────────────────────────────────
    lines += ["## 핵심 주제", ""]
    for t in topics:
        related = t.get("related_topics", [])
        backlinks = " / ".join(f"[[{r}]]" for r in related)
        lines.append(f"### {t['name']} `{t.get('category', '')}`")
        if t.get("summary"):
            lines.append(t["summary"])
        if backlinks:
            lines.append(f"관련: {backlinks}")
        lines.append("")

    # ── 결정 사항 ─────────────────────────────────────────────────────────────
    lines += ["## 결정 사항", ""]
    if decisions:
        for d in decisions:
            lines.append(f"- **{d['description']}**")
            if d.get("rationale"):
                lines.append(f"  > 근거: {d['rationale']}")
            if d.get("related_topics"):
                links = " ".join(f"[[{t}]]" for t in d["related_topics"])
                lines.append(f"  관련: {links}")
    else:
        lines.append("(없음)")
    lines.append("")

    # ── 액션 아이템 ───────────────────────────────────────────────────────────
    lines += ["## 액션 아이템", ""]
    if action_items:
        for a in action_items:
            checkbox = "- [ ]"
            owner = f"**{a['owner']}**" if a.get("owner") else ""
            deadline = f"마감: `{a['deadline']}`" if a.get("deadline") else ""
            parts = [p for p in [owner, a["description"], deadline] if p]
            lines.append(f"{checkbox} {' — '.join(parts)}")
    else:
        lines.append("(없음)")
    lines.append("")

    # ── 주요 엔티티 ───────────────────────────────────────────────────────────
    if entities:
        lines += ["## 주요 엔티티", ""]
        for e in entities:
            lines.append(f"- `{e.get('type', '')}` **{e['name']}**")
        lines.append("")

    # ── AI 요약 ───────────────────────────────────────────────────────────────
    lines += ["## AI 요약", ""]
    lines.append(summary or "(요약 없음)")
    lines.append("")

    # ── 메타 ──────────────────────────────────────────────────────────────────
    lines += [
        "---",
        f"*Generated by Meeting Summarizer + GraphRAG — {generated_at}*",
    ]
    if node_count or edge_count:
        lines.append(f"*Graph: {node_count} nodes, {edge_count} relationships*")

    # ── 파일 저장 ─────────────────────────────────────────────────────────────
    filename = f"{date_str}_{_safe_filename(title)}.md"
    filepath = target_dir / filename
    filepath.write_text("\n".join(lines), encoding="utf-8")
    return str(filepath)
